version: '3.8'
services:
  xds-mediator:
    container_name: xds-mediator
    hostname: xds-mediator
    image: xds-mediator:latest
    volumes:
      #data is the directory which you want to persist the generated parquet files
      - ../data:/tmp