version: '3.8'
services:
  xds-mediator:
    container_name: xds-mediator
    hostname: xds-mediator
    image: ghcr.io/isanteplus/openhim-mediator-xds:local
    ports:
      - "8050:8050"
      - "1044:1044"
    volumes:
      #data is the directory which you want to persist the generated parquet files
      - ./src/main/resources/mediator.properties:/mediator.properties
    entrypoint: 'java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=1044 -jar /mediator-xds-1.1.0-SNAPSHOT-jar-with-dependencies.jar --conf /mediator.properties'
